import test from 'node:test';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import mysql from 'mysql2/promise';
import pg from 'pg';
import {spawnSync} from 'node:child_process';
import {tenantDDL,masterDDL} from '../src/schema.js';

test('MariaDB import verifies data, preserves identities, refuses overwrite',{skip:!process.env.MARIADB_IMPORT_TEST,timeout:60000},async()=>{
 const source=await mysql.createConnection({host:'127.0.0.1',port:53306,user:'root',password:'local-migration-test'});
 const target=new pg.Client({host:process.env.DB_HOST,port:Number(process.env.DB_PORT),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:'knockout'});
 await target.connect();const db=`knockout_import_test_${process.pid}`;await target.query(`CREATE DATABASE "${db}"`);
 try{
  // The MariaDB server is a disposable test container, never an application server.
  for(const [schema,ddl] of [['knockout_master',masterDDL],['knockout',tenantDDL]]){
   await source.query(`CREATE DATABASE ${schema} CHARACTER SET utf8mb4`);await source.query(`USE ${schema}`);
   for(const sql of ddl)await source.query(sql.replace(/ CHECK \(\w+ IN \([^)]*\)\)/g,'').replaceAll('BIGINT GENERATED BY DEFAULT AS IDENTITY','INT AUTO_INCREMENT').replaceAll('TIMESTAMP WITH TIME ZONE','DATETIME(6)').replaceAll('JSONB','JSON'));
  }
  await source.query("INSERT INTO knockout.settings(id,hotel_name) VALUES(1,'Import test')");
  await source.query("INSERT INTO knockout.users(id,name,role,pin,active) VALUES(42,'Inactive user','admin','123456',false)");
  await source.query("INSERT INTO knockout.menu_items(id,name,category,price) VALUES(27,'Café test','Main',123.45)");
  await source.query("INSERT INTO knockout_master.companies(id,company_name,database_name,hotel_id,modules,admin_name) VALUES(9,'Import test','knockout','IMPT','[\"tables\",\"billing\"]','Owner')");
  const env={...process.env,PGDATABASE:db,SOURCE_DB_HOST:'127.0.0.1',SOURCE_DB_PORT:'53306',SOURCE_DB_USER:'root',SOURCE_DB_PASSWORD:'local-migration-test'};
  const run=()=>spawnSync(process.execPath,[fileURLToPath(new URL('../scripts/migrate-mariadb.mjs',import.meta.url)),'--confirm-source-readonly'],{env,encoding:'utf8'});
  const result=run();assert.equal(result.status,0,result.stderr);const report=JSON.parse(result.stdout);assert.equal(report.tables.length,25);assert(report.tables.every(row=>row.verified));
  const check=new pg.Client({host:process.env.DB_HOST,port:Number(process.env.DB_PORT),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:db});await check.connect();
  try{assert.equal((await check.query('SELECT active FROM knockout.users WHERE id=42')).rows[0].active,false);assert.equal((await check.query("INSERT INTO knockout.menu_items(name,category,price) VALUES('Next','Main',5) RETURNING id")).rows[0].id,28)}finally{await check.end()}
  const rerun=run();assert.notEqual(rerun.status,0);assert.match(rerun.stderr,/already exists/);
 }finally{await source.query("DROP DATABASE IF EXISTS knockout");await source.query("DROP DATABASE IF EXISTS knockout_master");await source.end();await target.query(`DROP DATABASE "${db}" WITH (FORCE)`);await target.end()}
});
