const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const seed = {
  tables: Array.from({length:20},(_,i)=>({id:i+1,name:`Table ${String(i+1).padStart(2,'0')}`,seats:[2,4,4,6,2][i%5],floor:i<12?'Ground Floor':'Rooftop',status:i%6===0?'reserved':i%3===0?'occupied':'available',guest:i%6===0?['Meera Shah','Vikram Rao','Sara Khan'][i%3]:i%3===0?['Walk-in Guest','Aarav Patel','Nisha Singh'][i%3]:'',time:i%6===0?'8:30 PM':i%3===0?`${22+i} min`:'Ready'})),
  menu:[
    {id:1,name:'Truffle Mushroom Soup',cat:'Starters',price:320,icon:'🍲',desc:'Wild mushrooms, truffle cream'},
    {id:2,name:'Burrata Garden Salad',cat:'Starters',price:440,icon:'🥗',desc:'Heirloom tomato, basil oil'},
    {id:3,name:'Tandoori Paneer',cat:'Starters',price:390,icon:'🍢',desc:'Charred peppers, mint chutney'},
    {id:4,name:'Herb Roasted Chicken',cat:'Mains',price:680,icon:'🍗',desc:'Potato purée, seasonal greens'},
    {id:5,name:'Forest Risotto',cat:'Mains',price:570,icon:'🍚',desc:'Porcini, parmesan, herbs'},
    {id:6,name:'Coastal Fish Curry',cat:'Mains',price:720,icon:'🍛',desc:'Coconut, kokum, steamed rice'},
    {id:7,name:'Classic Tiramisu',cat:'Desserts',price:350,icon:'🍰',desc:'Mascarpone, espresso, cocoa'},
    {id:8,name:'Chocolate Fondant',cat:'Desserts',price:390,icon:'🍫',desc:'Warm centre, vanilla bean'},
    {id:9,name:'Virgin Mojito',cat:'Beverages',price:220,icon:'🍹',desc:'Lime, mint, sparkling water'},
    {id:10,name:'Cold Brew Tonic',cat:'Beverages',price:260,icon:'☕',desc:'Single origin coffee, tonic'},
    {id:11,name:'Butter Naan',cat:'Sides',price:95,icon:'🫓',desc:'Tandoor baked, cultured butter'},
    {id:12,name:'Steamed Rice',cat:'Sides',price:160,icon:'🍚',desc:'Aromatic basmati rice'}],
  inventory:[
    {id:1,name:'Basmati Rice',sku:'GR-001',cat:'Grains',qty:42,unit:'kg',min:15,cost:110,supplier:'Shree Foods'},
    {id:2,name:'Chicken Breast',sku:'MT-014',cat:'Meat',qty:8,unit:'kg',min:12,cost:310,supplier:'Fresh Farms'},
    {id:3,name:'Wild Mushrooms',sku:'VG-031',cat:'Vegetables',qty:5,unit:'kg',min:6,cost:620,supplier:'Green Basket'},
    {id:4,name:'Cooking Cream',sku:'DY-008',cat:'Dairy',qty:18,unit:'L',min:8,cost:180,supplier:'Daily Dairy'},
    {id:5,name:'Arabica Coffee',sku:'BV-022',cat:'Beverages',qty:14,unit:'kg',min:5,cost:840,supplier:'Hill Roasters'},
    {id:6,name:'Paneer',sku:'DY-011',cat:'Dairy',qty:7,unit:'kg',min:8,cost:360,supplier:'Daily Dairy'},
    {id:7,name:'Tomatoes',sku:'VG-002',cat:'Vegetables',qty:21,unit:'kg',min:10,cost:55,supplier:'Green Basket'},
    {id:8,name:'Olive Oil',sku:'OL-009',cat:'Oils',qty:9,unit:'L',min:4,cost:720,supplier:'Gourmet Trade'}],
  orders:[
    {id:'ORD-1048',table:'Table 04',customer:'Walk-in Guest',amount:1840,status:'served',time:'12:42 PM'},
    {id:'ORD-1047',table:'Table 12',customer:'Aarav Patel',amount:2360,status:'preparing',time:'12:34 PM'},
    {id:'ORD-1046',table:'Table 09',customer:'Nisha Singh',amount:1270,status:'pending',time:'12:28 PM'},
    {id:'ORD-1045',table:'Takeaway',customer:'Rohit Mehta',amount:890,status:'served',time:'12:15 PM'}],
  settings:{name:'Olive & Oak',phone:'+91 98765 43210',email:'hello@oliveandoak.in',address:'42 Garden Avenue, Bengaluru, Karnataka',gst:'29ABCDE1234F1Z5',tax:5,service:5}
};
let db = JSON.parse(localStorage.getItem('oliveOakDB')||'null') || seed;
let state={view:'dashboard',cart:[],category:'All',floor:'All',stockFilter:'All'};
const save=()=>localStorage.setItem('oliveOakDB',JSON.stringify(db));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function modal(html){const m=$('#modal');m.innerHTML=`<div class="modal-box">${html}</div>`;m.classList.add('open');$$('[data-close]',m).forEach(b=>b.onclick=()=>m.classList.remove('open'))}
function head(kicker,title,sub,actions=''){return `<div class="page-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`}
function setView(view){state.view=view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#sidebar').classList.remove('open');render()}
function dashboard(){
 const occupied=db.tables.filter(t=>t.status==='occupied').length, low=db.inventory.filter(i=>i.qty<=i.min).length, sales=db.orders.reduce((s,o)=>s+o.amount,0);
 return `${head('TODAY · LIVE OVERVIEW','Good afternoon, Arjun','Here’s what is happening at Olive & Oak today.',`<button class="btn" data-go="reports">View reports</button><button class="btn primary" data-go="billing">+ New order</button>`)}
 <div class="metrics">
 ${metric('₹','Today’s Revenue',money(sales+18420),'+12.4%')}${metric('▦','Active Tables',`${occupied} / ${db.tables.length}`,'Live')}${metric('⌑','Orders Today',db.orders.length+38,'+8.2%')}${metric('!','Low Stock Items',low,low?'Needs attention':'All good')}
 </div><div class="grid-2"><div class="card"><div class="card-head"><div><h2>Revenue Overview</h2><p>Daily revenue compared to last week</p></div><button class="chip">This week⌄</button></div>${bars()}</div><div class="card"><div class="card-head"><div><h2>Table Occupancy</h2><p>Current floor status</p></div><button class="link-btn" data-go="tables">Manage tables →</button></div><div class="donut-row"><div class="donut"></div><div class="legend-list"><div><i></i>Occupied<strong>${occupied}</strong></div><div><i></i>Reserved<strong>${db.tables.filter(t=>t.status==='reserved').length}</strong></div><div><i></i>Cleaning<strong>3</strong></div><div><i></i>Available<strong>${db.tables.filter(t=>t.status==='available').length}</strong></div></div></div></div></div>
 <div class="grid-2 grid-even"><div class="card"><div class="card-head"><div><h2>Recent Orders</h2><p>Latest activity from your restaurant</p></div><button class="link-btn" data-go="orders">View all →</button></div>${ordersTable(db.orders.slice(0,4))}</div><div class="card"><div class="card-head"><div><h2>Recent Activity</h2><p>Updates across your restaurant</p></div></div><div class="activity-list">${activities()}</div></div></div>`}
function metric(icon,label,value,trend){return `<div class="metric"><div class="icon">${icon}</div><small>${label}</small><strong>${value}</strong><span class="trend">${trend}</span><svg class="mini" viewBox="0 0 60 24"><path d="M1 20 C10 15,13 18,20 12 S31 18,38 9 S48 12,59 3" fill="none" stroke="#6a9679" stroke-width="2"/></svg></div>`}
function bars(){let a=[56,72,48,86,64,92,76];return `<div class="bar-chart">${a.map((v,i)=>`<div class="bar-wrap"><div class="bar prev" style="height:${v*.72}%"></div><div class="bar" style="height:${v}%"></div><label>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</label></div>`).join('')}</div><div class="chart-legend"><span><i></i>This week ₹1.82L</span><span><i></i>Last week ₹1.54L</span></div>`}
function activities(){return [['✓','Payment received','Table 04 · ₹1,840','2 min'],['▦','Table seated','Table 12 · 4 guests','8 min'],['!','Low stock alert','Chicken Breast · 8 kg','15 min'],['⌑','Order completed','ORD-1045 · Takeaway','24 min']].map(a=>`<div class="activity"><div class="dot">${a[0]}</div><div><strong>${a[1]}</strong><small>${a[2]}</small></div><time>${a[3]}</time></div>`).join('')}
function tables(){let list=db.tables.filter(t=>state.floor==='All'||t.floor===state.floor);return `${head('FLOOR OPERATIONS','Table Management','Live seating, reservations, and service status.',`<button class="btn" id="reserveBtn">+ Reservation</button><button class="btn primary" id="addTableBtn">+ Add table</button>`)}<div class="floor-tabs">${['All','Ground Floor','Rooftop'].map(x=>`<button class="chip ${state.floor===x?'active':''}" data-floor="${x}">${x}</button>`).join('')}</div><div class="tables-grid">${list.map(t=>`<div class="table-card ${t.status}" data-table="${t.id}"><div class="top"><h3>${t.name}</h3><span class="status ${t.status==='reserved'?'neutral':t.status==='occupied'?'pending':''}">${t.status}</span></div><div class="guest">${t.guest||'Ready for guests'}</div><div class="meta"><span>♙ ${t.seats} seats</span><span>${t.time}</span></div></div>`).join('')}</div>`}
function billing(){let cats=['All',...new Set(db.menu.map(x=>x.cat))], list=db.menu.filter(x=>state.category==='All'||x.cat===state.category);return `${head('POINT OF SALE','Billing & POS','Create orders, manage items, and settle bills.',`<button class="btn" id="clearCart">Clear order</button>`)}<div class="pos-layout"><div><div class="filter-row">${cats.map(c=>`<button class="chip ${state.category===c?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div><div class="menu-grid">${list.map(x=>`<div class="menu-item" data-menu="${x.id}"><div class="food-icon">${x.icon}</div><h4>${x.name}</h4><p>${x.desc}</p><strong>${money(x.price)}</strong></div>`).join('')}</div></div><div class="card cart"><div class="card-head"><div><h2>Current Order</h2><p>Dine-in · Select a table</p></div><select class="form-control" id="cartTable"><option>Takeaway</option>${db.tables.map(t=>`<option>${t.name}</option>`).join('')}</select></div><div class="cart-items">${cartHtml()}</div>${totalsHtml()}</div></div>`}
function cartHtml(){if(!state.cart.length)return `<div class="empty"><div style="font-size:34px">⌑</div><p>Your order is empty</p><small>Select items from the menu to begin</small></div>`;return state.cart.map(c=>{let x=db.menu.find(m=>m.id===c.id);return `<div class="cart-item"><div><h4>${x.name}</h4><div class="qty"><button data-qty="${x.id}" data-delta="-1">−</button><span>${c.qty}</span><button data-qty="${x.id}" data-delta="1">+</button></div></div><strong>${money(x.price*c.qty)}</strong></div>`}).join('')}
function totals(){let subtotal=state.cart.reduce((s,c)=>s+db.menu.find(m=>m.id===c.id).price*c.qty,0),tax=subtotal*(db.settings.tax/100),service=subtotal*(db.settings.service/100);return{subtotal,tax,service,total:subtotal+tax+service}}
function totalsHtml(){let t=totals();return `<div class="totals"><div class="total-line"><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div class="total-line"><span>GST (${db.settings.tax}%)</span><b>${money(t.tax)}</b></div><div class="total-line"><span>Service charge (${db.settings.service}%)</span><b>${money(t.service)}</b></div><div class="total-line grand"><span>Total</span><span>${money(t.total)}</span></div><button class="btn primary pay-btn" id="payBtn" ${!state.cart.length?'disabled':''}>Proceed to payment →</button></div>`}
function inventory(){let list=db.inventory.filter(x=>state.stockFilter==='All'||(state.stockFilter==='Low'&&x.qty<=x.min)||x.cat===state.stockFilter);return `${head('INVENTORY CONTROL','Stock Management','Track ingredients, costs, suppliers, and reorder levels.',`<button class="btn" id="stockReport">Export CSV</button><button class="btn primary" id="addStock">+ Add item</button>`)}<div class="metrics">${metric('□','Total Items',db.inventory.length,'SKUs')}${metric('!','Low Stock',db.inventory.filter(x=>x.qty<=x.min).length,'Action needed')}${metric('₹','Stock Value',money(db.inventory.reduce((s,x)=>s+x.qty*x.cost,0)),'Current')}${metric('↻','Suppliers',new Set(db.inventory.map(x=>x.supplier)).size,'Active')}</div><div class="card"><div class="inventory-toolbar"><input id="stockSearch" placeholder="Search item, SKU, or supplier..."><select class="form-control" id="stockFilter"><option>All</option><option>Low</option>${[...new Set(db.inventory.map(x=>x.cat))].map(x=>`<option>${x}</option>`).join('')}</select></div>${inventoryTable(list)}</div>`}
function inventoryTable(list){return `<table class="table"><thead><tr><th>Item</th><th>Category</th><th>In Stock</th><th>Level</th><th>Unit Cost</th><th>Supplier</th><th></th></tr></thead><tbody>${list.map(x=>`<tr><td><div class="table-name"><div class="tiny-icon">□</div><div><b>${x.name}</b><br><small>${x.sku}</small></div></div></td><td>${x.cat}</td><td><b>${x.qty} ${x.unit}</b></td><td><div class="stock-level ${x.qty<=x.min?'low':''}"><i style="width:${Math.min(100,x.qty/x.min*55)}%"></i></div><small>${x.qty<=x.min?'Reorder':'Healthy'}</small></td><td>${money(x.cost)}</td><td>${x.supplier}</td><td><button class="link-btn" data-stock="${x.id}">Adjust</button></td></tr>`).join('')}</tbody></table>`}
function ordersTable(list){return `<table class="table"><thead><tr><th>Order</th><th>Table</th><th>Customer</th><th>Amount</th><th>Status</th><th>Time</th></tr></thead><tbody>${list.map(o=>`<tr><td><b>${o.id}</b></td><td>${o.table}</td><td>${o.customer}</td><td><b>${money(o.amount)}</b></td><td><span class="status ${o.status==='pending'||o.status==='preparing'?'pending':''}">${o.status}</span></td><td>${o.time}</td></tr>`).join('')}</tbody></table>`}
function orders(){return `${head('ORDER DESK','All Orders','Track kitchen progress and completed bills.',`<button class="btn primary" data-go="billing">+ New order</button>`)}<div class="filter-row">${['All','Pending','Preparing','Served'].map(x=>`<button class="chip ${x==='All'?'active':''}">${x}</button>`).join('')}</div><div class="card">${ordersTable(db.orders)}</div>`}
function reports(){let revenue=db.orders.reduce((s,o)=>s+o.amount,0)+18420;return `${head('BUSINESS INTELLIGENCE','Reports & Analytics','Revenue, sales performance, and operational trends.',`<button class="btn" id="printReport">Print report</button>`)}<div class="metrics">${metric('₹','Gross Sales',money(revenue),'+12.4%')}${metric('⌑','Average Bill',money(revenue/(db.orders.length+8)),'+4.1%')}${metric('♙','Guests Served',126,'+9.8%')}${metric('↗','Table Turnover','2.8x','+0.3')}</div><div class="grid-2"><div class="card"><div class="card-head"><div><h2>Sales Performance</h2><p>Seven-day comparison</p></div></div>${bars()}</div><div class="card"><div class="card-head"><div><h2>Best Sellers</h2><p>Top menu items this week</p></div></div>${db.menu.slice(0,5).map((x,i)=>`<div class="activity"><div class="dot">${i+1}</div><div><strong>${x.name}</strong><small>${x.cat}</small></div><b>${28-i*3} sold</b></div>`).join('')}</div></div>`}
function admin(){let s=db.settings;return `${head('SYSTEM CONTROL','Admin Panel','Manage business details, tax rules, users, and preferences.',`<button class="btn primary" id="saveSettings">Save changes</button>`)}<div class="admin-grid"><div class="card settings-nav"><button class="active">Business profile</button><button>Tax & billing</button><button>User management</button><button>Menu settings</button><button>Notifications</button><button>Security</button></div><div class="card"><div class="card-head"><div><h2>Business Profile</h2><p>Details shown on bills and customer receipts</p></div></div><div class="form-grid"><div class="field"><label>Business name</label><input class="form-control" id="setName" value="${s.name}"></div><div class="field"><label>GST number</label><input class="form-control" id="setGst" value="${s.gst}"></div><div class="field"><label>Phone</label><input class="form-control" id="setPhone" value="${s.phone}"></div><div class="field"><label>Email</label><input class="form-control" id="setEmail" value="${s.email}"></div><div class="field full"><label>Address</label><input class="form-control" id="setAddress" value="${s.address}"></div><div class="field"><label>GST rate (%)</label><input class="form-control" type="number" id="setTax" value="${s.tax}"></div><div class="field"><label>Service charge (%)</label><input class="form-control" type="number" id="setService" value="${s.service}"></div></div><hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><div class="card-head"><div><h2>Data Management</h2><p>Reset this demo to its original records</p></div><button class="btn danger" id="resetData">Reset demo data</button></div></div></div>`}
function render(){const views={dashboard,tables,billing,inventory,orders,reports,admin};$('#app').innerHTML=views[state.view]();bind()}
function bind(){
 $$('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$$('[data-floor]').forEach(b=>b.onclick=()=>{state.floor=b.dataset.floor;render()});$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()});
 $$('[data-table]').forEach(c=>c.onclick=()=>editTable(+c.dataset.table));$$('[data-menu]').forEach(c=>c.onclick=()=>{let id=+c.dataset.menu,found=state.cart.find(x=>x.id===id);found?found.qty++:state.cart.push({id,qty:1});render();toast('Item added to order')});
 $$('[data-qty]').forEach(b=>b.onclick=e=>{e.stopPropagation();let c=state.cart.find(x=>x.id===+b.dataset.qty);c.qty+=+b.dataset.delta;if(c.qty<=0)state.cart=state.cart.filter(x=>x!==c);render()});
 $$('[data-stock]').forEach(b=>b.onclick=()=>adjustStock(+b.dataset.stock));
 if($('#clearCart'))$('#clearCart').onclick=()=>{state.cart=[];render()};if($('#payBtn'))$('#payBtn').onclick=checkout;if($('#addTableBtn'))$('#addTableBtn').onclick=addTable;if($('#reserveBtn'))$('#reserveBtn').onclick=reserve;
 if($('#addStock'))$('#addStock').onclick=addStock;if($('#stockReport'))$('#stockReport').onclick=exportStock;if($('#printReport'))$('#printReport').onclick=()=>window.print();
 if($('#stockFilter'))$('#stockFilter').onchange=e=>{state.stockFilter=e.target.value;render()};if($('#stockSearch'))$('#stockSearch').oninput=e=>{let q=e.target.value.toLowerCase();$$('tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};
 if($('#saveSettings'))$('#saveSettings').onclick=saveSettings;if($('#resetData'))$('#resetData').onclick=()=>{if(confirm('Reset all application data?')){db=structuredClone(seed);save();render();toast('Demo data reset')}};
}
function editTable(id){let t=db.tables.find(x=>x.id===id);modal(`<h2>${t.name}</h2><p>${t.floor} · ${t.seats} seats</p><div class="field"><label>Guest / reservation name</label><input class="form-control" id="guestEdit" value="${t.guest}"></div><div class="field" style="margin-top:12px"><label>Status</label><select class="form-control" id="statusEdit"><option>available</option><option>occupied</option><option>reserved</option></select></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="tableSave">Update table</button></div>`);$('#statusEdit').value=t.status;$('#tableSave').onclick=()=>{t.guest=$('#guestEdit').value;t.status=$('#statusEdit').value;t.time=t.status==='available'?'Ready':t.status==='reserved'?'Upcoming':'Just seated';save();$('#modal').classList.remove('open');render();toast('Table updated')}}
function addTable(){modal(`<h2>Add a table</h2><p>Create a new table on your floor plan.</p><div class="form-grid"><div class="field"><label>Name</label><input id="newTableName" class="form-control" placeholder="Table 21"></div><div class="field"><label>Seats</label><input id="newSeats" class="form-control" type="number" value="4"></div><div class="field full"><label>Floor</label><select id="newFloor" class="form-control"><option>Ground Floor</option><option>Rooftop</option></select></div></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="createTable">Create</button></div>`);$('#createTable').onclick=()=>{db.tables.push({id:Date.now(),name:$('#newTableName').value||`Table ${db.tables.length+1}`,seats:+$('#newSeats').value,floor:$('#newFloor').value,status:'available',guest:'',time:'Ready'});save();$('#modal').classList.remove('open');render();toast('Table created')}}
function reserve(){modal(`<h2>New reservation</h2><p>Reserve an available table for a guest.</p><div class="form-grid"><div class="field"><label>Guest name</label><input id="resGuest" class="form-control"></div><div class="field"><label>Table</label><select id="resTable" class="form-control">${db.tables.filter(t=>t.status==='available').map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="field full"><label>Time</label><input id="resTime" type="time" class="form-control" value="20:00"></div></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="makeRes">Reserve</button></div>`);$('#makeRes').onclick=()=>{let t=db.tables.find(x=>x.id===+$('#resTable').value);t.status='reserved';t.guest=$('#resGuest').value||'Reserved Guest';t.time=$('#resTime').value;save();$('#modal').classList.remove('open');render();toast('Reservation confirmed')}}
function checkout(){let t=totals(),table=$('#cartTable').value,id=`ORD-${1049+db.orders.length}`;modal(`<div class="receipt"><span class="eyebrow">PAYMENT SUCCESSFUL</span><h2>${db.settings.name}</h2><p>${id} · ${table}</p><hr><div class="receipt-lines">${state.cart.map(c=>{let x=db.menu.find(m=>m.id===c.id);return `<div><span>${c.qty} × ${x.name}</span><b>${money(c.qty*x.price)}</b></div>`}).join('')}</div><hr><p>Total paid</p><div class="big-number">${money(t.total)}</div><p>Thank you for dining with us.</p><div class="modal-actions"><button class="btn" onclick="window.print()">Print receipt</button><button class="btn primary" data-close>Done</button></div></div>`);db.orders.unshift({id,table,customer:'Walk-in Guest',amount:Math.round(t.total),status:'served',time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});let tb=db.tables.find(x=>x.name===table);if(tb){tb.status='available';tb.guest='';tb.time='Ready'}state.cart=[];save();bind();render()}
function adjustStock(id){let x=db.inventory.find(i=>i.id===id);modal(`<h2>Adjust stock</h2><p>${x.name} · Current ${x.qty} ${x.unit}</p><div class="field"><label>New quantity (${x.unit})</label><input id="newQty" class="form-control" type="number" step=".1" value="${x.qty}"></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="stockSave">Update stock</button></div>`);$('#stockSave').onclick=()=>{x.qty=+$('#newQty').value;save();$('#modal').classList.remove('open');render();toast('Stock updated')}}
function addStock(){modal(`<h2>Add inventory item</h2><p>Create a new stock keeping unit.</p><div class="form-grid"><div class="field"><label>Item name</label><input id="iName" class="form-control"></div><div class="field"><label>SKU</label><input id="iSku" class="form-control"></div><div class="field"><label>Category</label><input id="iCat" class="form-control"></div><div class="field"><label>Quantity</label><input id="iQty" type="number" class="form-control"></div><div class="field"><label>Unit cost</label><input id="iCost" type="number" class="form-control"></div><div class="field"><label>Supplier</label><input id="iSupplier" class="form-control"></div></div><div class="modal-actions"><button class="btn" data-close>Cancel</button><button class="btn primary" id="itemCreate">Add item</button></div>`);$('#itemCreate').onclick=()=>{db.inventory.push({id:Date.now(),name:$('#iName').value||'New Item',sku:$('#iSku').value||'NEW-001',cat:$('#iCat').value||'Other',qty:+$('#iQty').value||0,unit:'kg',min:5,cost:+$('#iCost').value||0,supplier:$('#iSupplier').value||'Unassigned'});save();$('#modal').classList.remove('open');render();toast('Inventory item added')}}
function exportStock(){let csv='Item,SKU,Category,Quantity,Unit,Cost,Supplier\n'+db.inventory.map(x=>[x.name,x.sku,x.cat,x.qty,x.unit,x.cost,x.supplier].join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='olive-oak-inventory.csv';a.click();toast('Inventory exported')}
function saveSettings(){db.settings={name:$('#setName').value,gst:$('#setGst').value,phone:$('#setPhone').value,email:$('#setEmail').value,address:$('#setAddress').value,tax:+$('#setTax').value,service:+$('#setService').value};save();toast('Settings saved')}
$$('.nav-item').forEach(x=>x.onclick=()=>setView(x.dataset.view));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#today').textContent=new Date().toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'});$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){let q=e.target.value.toLowerCase();let table=db.tables.find(t=>t.name.toLowerCase().includes(q));if(table){setView('tables');setTimeout(()=>editTable(table.id),50)}else toast('No matching table found')}};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')$('#modal').classList.remove('open')});render();
