import express from 'express';
import cors from 'cors';
import multer from 'multer';
import crypto from 'node:crypto';
import {pool, migrate, getState, runWithTenant} from './database.js';
import {minio, bucket, initializeStorage, publicUrl} from './storage.js';

const app = express();
const portalRole = process.env.PORTAL_ROLE || 'admin';
const upload = multer({storage: multer.memoryStorage(), limits:{fileSize:5*1024*1024}, fileFilter:(_req,file,cb)=>cb(null,file.mimetype.startsWith('image/'))});
app.use(cors()); app.use(express.json());
app.use((req,_res,next)=>{const requested=String(req.headers['x-company-database']||process.env.DB_NAME||'knockout').toLowerCase();const database=/^knockout(?:_[0-9]+)?$/.test(requested)?requested:(process.env.DB_NAME||'knockout');runWithTenant(database,next)});

const asyncRoute = fn => (req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
async function ensureUniquePortalPin({pin,currentDatabase,excludeId=null}){
  const[[masterUsed]]=await pool.query('SELECT id,name FROM knockout_master.master_users WHERE pin=? LIMIT 1',[String(pin)]);
  if(masterUsed)throw Object.assign(new Error('This PIN is already assigned to a KnockOUT Master user. Choose another six-digit PIN.'),{status:409});
  const[schemas]=await pool.query("SELECT SCHEMA_NAME databaseName FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='knockout' OR SCHEMA_NAME REGEXP '^knockout_[0-9]+$'");
  for(const schema of schemas){
    const databaseName=schema.databaseName;
    if(!/^knockout(?:_[0-9]+)?$/.test(databaseName))continue;
    const params=[String(pin)];
    let sql=`SELECT id,name FROM \`${databaseName}\`.users WHERE pin=? AND deleted_at IS NULL`;
    if(databaseName===currentDatabase&&excludeId){sql+=' AND id<>?';params.push(excludeId)}
    sql+=' LIMIT 1';
    const[[used]]=await pool.query(sql,params);
    if(used)throw Object.assign(new Error('This PIN is already assigned to another KnockOUT user. Choose a globally unique six-digit PIN.'),{status:409});
  }
}
async function billFor(orderId, conn=pool) {
  const [[settings]] = await conn.query('SELECT tax_rate taxRate FROM settings WHERE id=1');
  const [items] = await conn.query('SELECT oi.menu_id menuId,oi.quantity qty,oi.note,oi.price,m.name,m.icon,m.image_url imageUrl FROM order_items oi JOIN menu_items m ON m.id=oi.menu_id WHERE oi.order_id=?',[orderId]);
  const subtotal=items.reduce((s,i)=>s+Number(i.price)*i.qty,0),tax=subtotal*Number(settings.taxRate)/100,service=0;
  return {items:items.map(i=>({...i,price:Number(i.price)})),subtotal,tax,service,total:subtotal+tax};
}
const isJuiceCategory=category=>String(category||'').trim().toLowerCase()==='juices';
async function refreshOrderProductionStatus(orderId,conn=pool){
  const[lines]=await conn.query('SELECT production_status itemStatus FROM order_items WHERE order_id=?',[orderId]);
  if(!lines.length)return 'new';
  const next=lines.every(line=>line.itemStatus==='ready')?'ready':lines.every(line=>line.itemStatus==='new')?'new':'preparing';
  await conn.query("UPDATE orders SET status=? WHERE id=? AND status IN ('new','preparing','ready')",[next,orderId]);
  return next;
}
async function sendBookingConfirmation(phone,message){
  const url=String(process.env.SMS_WEBHOOK_URL||'').trim();
  if(!url)return {status:'queued',detail:'SMS gateway is not configured'};
  const headers={'content-type':'application/json'};
  if(process.env.SMS_WEBHOOK_TOKEN)headers.authorization=`Bearer ${process.env.SMS_WEBHOOK_TOKEN}`;
  const response=await fetch(url,{method:'POST',headers,body:JSON.stringify({to:phone,message,channel:'sms',source:'KnockOUT'})});
  if(!response.ok)throw new Error(`SMS gateway returned ${response.status}`);
  return {status:'sent'};
}

app.get('/api/health', asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({ok:true,service:`knockout-${portalRole}-api`,portal:portalRole,database:'mariadb',storage:'minio'})}));
app.get('/api/state', asyncRoute(async(req,res)=>{const state=await getState();state.companyDatabase=String(req.headers['x-company-database']||process.env.DB_NAME||'knockout');if(portalRole!=='admin'){delete state.inventory;delete state.inventoryTransactions;delete state.financeEntries;delete state.users;delete state.attendance}res.json(state)}));
app.post('/api/login', asyncRoute(async(req,res)=>{const [[user]]=await pool.query('SELECT id,name,role FROM users WHERE role=? AND pin=? AND active=1 AND deleted_at IS NULL',[portalRole,req.body.pin]);if(!user)return res.status(401).json({message:`Invalid ${portalRole} portal PIN`});res.json(user)}));
app.post('/api/bookings', asyncRoute(async(req,res)=>{
  if(portalRole!=='admin')return res.status(403).json({message:'Only Admin can create table bookings'});
  const tableId=Number(req.body.tableId),bookingDate=String(req.body.bookingDate||''),bookingTime=String(req.body.bookingTime||''),durationMinutes=Number(req.body.durationMinutes||90),customerPhone=String(req.body.customerPhone||'').replace(/[\s()-]/g,'');
  if(!tableId||!/^\d{4}-\d{2}-\d{2}$/.test(bookingDate)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(bookingTime)||!Number.isInteger(durationMinutes)||durationMinutes<30||durationMinutes>240||!/^\+?\d{8,15}$/.test(customerPhone))return res.status(400).json({message:'Table, future date, time, 30–240 minute duration, and a valid customer phone are required'});
  const conn=await pool.getConnection();let bookingId,message;
  try{
    await conn.beginTransaction();
    const[[table]]=await conn.query('SELECT id,table_number number,active FROM restaurant_tables WHERE id=? FOR UPDATE',[tableId]);
    if(!table||!table.active)throw Object.assign(new Error('Table is not available'),{status:404});
    const[[timeCheck]]=await conn.query('SELECT TIMESTAMP(?,?) <= NOW() inPast',[bookingDate,bookingTime]);
    if(timeCheck.inPast)throw Object.assign(new Error('Choose a future booking date and time'),{status:400});
    const[[conflict]]=await conn.query("SELECT id,booking_time bookingTime,duration_minutes durationMinutes FROM bookings WHERE table_id=? AND booking_date=? AND status='confirmed' AND TIMESTAMP(booking_date,booking_time) < DATE_ADD(TIMESTAMP(?,?),INTERVAL ? MINUTE) AND DATE_ADD(TIMESTAMP(booking_date,booking_time),INTERVAL duration_minutes MINUTE) > TIMESTAMP(?,?) LIMIT 1 FOR UPDATE",[tableId,bookingDate,bookingDate,bookingTime,durationMinutes,bookingDate,bookingTime]);
    if(conflict)throw Object.assign(new Error(`Table ${table.number} is already locked at that time`),{status:409});
    message=`KnockOUT booking confirmed: Table ${table.number} on ${bookingDate.split('-').reverse().join('-')} at ${bookingTime}, reserved for ${durationMinutes} minutes.`;
    const[result]=await conn.query("INSERT INTO bookings (table_id,guest_name,customer_phone,booking_date,booking_time,duration_minutes,status,notification_status,notification_message) VALUES (?,'Customer',?,?,?,?,'confirmed','queued',?)",[tableId,customerPhone,bookingDate,bookingTime,durationMinutes,message]);
    bookingId=result.insertId;
    await conn.commit();
  }catch(e){await conn.rollback();throw e}finally{conn.release()}
  let notification;
  try{notification=await sendBookingConfirmation(customerPhone,message)}catch(error){notification={status:'failed',detail:error.message}}
  await pool.query('UPDATE bookings SET notification_status=? WHERE id=?',[notification.status,bookingId]);
  res.status(201).json({ok:true,id:bookingId,notificationStatus:notification.status,notificationDetail:notification.detail||''});
}));
app.delete('/api/bookings/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Only Admin can cancel table bookings'});const[result]=await pool.query("UPDATE bookings SET status='cancelled' WHERE id=? AND status='confirmed'",[req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Active booking not found'});res.json({ok:true})}));
app.post('/api/orders', asyncRoute(async(req,res)=>{const conn=await pool.getConnection();try{await conn.beginTransaction();const [[table]]=await conn.query('SELECT * FROM restaurant_tables WHERE id=? FOR UPDATE',[req.body.tableId]);if(!table)throw Object.assign(new Error('Table not found'),{status:404});if(table.order_id)throw Object.assign(new Error('This table already has an active order'),{status:400});const[[activeBooking]]=await conn.query("SELECT id FROM bookings WHERE table_id=? AND status='confirmed' AND NOW() >= TIMESTAMP(booking_date,booking_time) AND NOW() < DATE_ADD(TIMESTAMP(booking_date,booking_time),INTERVAL duration_minutes MINUTE) LIMIT 1 FOR UPDATE",[table.id]);if(activeBooking)throw Object.assign(new Error('This table is locked for a confirmed reservation at the current time'),{status:409});const [result]=await conn.query("INSERT INTO orders (table_id,guest_name,waiter,status,payment_status,created_at) VALUES (?,?,?,'new','unpaid',NOW())",[table.id,req.body.guestName||table.guest_name||'Walk-in Guest',req.body.waiter||'Waiter']);for(const item of req.body.items){const [[menu]]=await conn.query('SELECT price FROM menu_items WHERE id=? AND available=1',[item.menuId]);if(!menu)throw new Error('Menu item unavailable');await conn.query('INSERT INTO order_items (order_id,menu_id,quantity,note,price) VALUES (?,?,?,?,?)',[result.insertId,item.menuId,item.qty,item.note||'',menu.price])}await conn.query("UPDATE restaurant_tables SET status='occupied',guest_name=?,booking_time='',order_id=? WHERE id=?",[req.body.guestName||table.guest_name||'Walk-in Guest',result.insertId,table.id]);await conn.commit();res.status(201).json({id:result.insertId,bill:await billFor(result.insertId)})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.post('/api/orders/:id/items', asyncRoute(async(req,res)=>{if(!['admin','waiter'].includes(portalRole))return res.status(403).json({message:'Only Admin or Waiter can add order items'});if(!req.body.items?.length)return res.status(400).json({message:'Add at least one item'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[[order]]=await conn.query('SELECT id,status FROM orders WHERE id=? FOR UPDATE',[req.params.id]);if(!order)throw Object.assign(new Error('Order not found'),{status:404});if(order.status==='completed')throw Object.assign(new Error('This order is already completed'),{status:409});for(const item of req.body.items){const qty=Math.max(1,Number(item.qty)||1),note=item.note||'';const[[menu]]=await conn.query('SELECT price FROM menu_items WHERE id=? AND available=1',[item.menuId]);if(!menu)throw Object.assign(new Error('Menu item unavailable'),{status:400});const[[line]]=await conn.query('SELECT id,quantity FROM order_items WHERE order_id=? AND menu_id=? AND note=? LIMIT 1',[order.id,item.menuId,note]);if(line)await conn.query("UPDATE order_items SET quantity=?,production_status='new' WHERE id=?",[line.quantity+qty,line.id]);else await conn.query('INSERT INTO order_items (order_id,menu_id,quantity,note,price) VALUES (?,?,?,?,?)',[order.id,item.menuId,qty,note,menu.price])}await conn.query("UPDATE orders SET status='new' WHERE id=?",[order.id]);await conn.commit();res.status(201).json({id:order.id,bill:await billFor(order.id)})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.patch('/api/tables/:id/status', asyncRoute(async(req,res)=>{if(!['admin','waiter'].includes(portalRole))return res.status(403).json({message:'Only Admin or Waiter can update tables'});const allowed=['available','occupied','reserved','cleaning'],status=req.body.status;if(!allowed.includes(status))return res.status(400).json({message:'Invalid table status'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[[table]]=await conn.query('SELECT * FROM restaurant_tables WHERE id=? FOR UPDATE',[req.params.id]);if(!table)throw Object.assign(new Error('Table not found'),{status:404});if(table.order_id&&status!=='occupied')throw Object.assign(new Error('Finalize the active bill before changing this table'),{status:409});if(status==='occupied'&&!table.order_id)throw Object.assign(new Error('Create an order to mark this table occupied'),{status:409});if(status==='reserved')await conn.query("UPDATE restaurant_tables SET status='reserved',guest_name='',booking_time=? WHERE id=?",[req.body.bookingTime||table.booking_time||'',table.id]);else if(status==='occupied')await conn.query("UPDATE restaurant_tables SET status='occupied' WHERE id=?",[table.id]);else await conn.query('UPDATE restaurant_tables SET status=?,guest_name=?,booking_time=? WHERE id=?',[status,'','',table.id]);await conn.commit();res.json({ok:true,status})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.post('/api/tables',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const number=Number(req.body.number),seats=Number(req.body.seats),area=String(req.body.area||'').trim();if(!Number.isInteger(number)||number<1||!Number.isInteger(seats)||seats<1||!area)return res.status(400).json({message:'Table number, seats, and service area are required'});const[[existing]]=await pool.query('SELECT id,active,order_id orderId FROM restaurant_tables WHERE table_number=?',[number]);if(existing?.active)return res.status(409).json({message:`Table ${number} already exists`});if(existing){await pool.query("UPDATE restaurant_tables SET seats=?,area=?,status='available',guest_name='',booking_time='',order_id=NULL,active=TRUE WHERE id=?",[seats,area,existing.id]);return res.status(201).json({id:existing.id,restored:true})}const[result]=await pool.query("INSERT INTO restaurant_tables (table_number,seats,area,status,active) VALUES (?,?,?,'available',TRUE)",[number,seats,area]);res.status(201).json({id:result.insertId})}));
app.delete('/api/tables/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const[[table]]=await pool.query('SELECT id,table_number number,order_id orderId FROM restaurant_tables WHERE id=? AND active=TRUE',[req.params.id]);if(!table)return res.status(404).json({message:'Table not found'});if(table.orderId)return res.status(409).json({message:'Finalize the active bill before deleting this table'});await pool.query("UPDATE bookings SET status='cancelled' WHERE table_id=? AND status='confirmed'",[table.id]);await pool.query("UPDATE restaurant_tables SET active=FALSE,status='available',guest_name='',booking_time='',order_id=NULL WHERE id=?",[table.id]);res.json({ok:true,number:table.number})}));
app.post('/api/parcels', asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Parcel orders are created by Admin'});if(!req.body.items?.length)return res.status(400).json({message:'Add at least one food item'});const paymentMethod=req.body.paymentMethod||null;if(paymentMethod&&!['Cash','Card / UPI'].includes(paymentMethod))return res.status(400).json({message:'Invalid payment method'});const conn=await pool.getConnection();try{await conn.beginTransaction();const [result]=await conn.query("INSERT INTO orders (table_id,order_type,guest_name,customer_phone,waiter,status,payment_status,payment_method,created_at) VALUES (NULL,'parcel',?,?,?,'new',?,?,NOW())",[req.body.customerName||'Parcel Customer',req.body.customerPhone||'',req.body.adminName||'Admin',paymentMethod?'paid':'unpaid',paymentMethod]);for(const item of req.body.items){const [[menu]]=await conn.query('SELECT price FROM menu_items WHERE id=? AND available=1',[item.menuId]);if(!menu)throw new Error('Menu item unavailable');await conn.query('INSERT INTO order_items (order_id,menu_id,quantity,note,price) VALUES (?,?,?,?,?)',[result.insertId,item.menuId,item.qty,item.note||'',menu.price])}const bill=await billFor(result.insertId,conn);if(paymentMethod)await conn.query('UPDATE orders SET subtotal=?,tax=?,service_charge=?,total=? WHERE id=?',[bill.subtotal,bill.tax,bill.service,bill.total,result.insertId]);await conn.commit();res.status(201).json({id:result.insertId,paymentStatus:paymentMethod?'paid':'unpaid',bill})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.post('/api/orders/:id/mark-paid',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Only Admin can record parcel payments'});if(!['Cash','Card / UPI'].includes(req.body.paymentMethod))return res.status(400).json({message:'Choose Cash or Card / UPI'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[[order]]=await conn.query('SELECT id,order_type,status,payment_status FROM orders WHERE id=? FOR UPDATE',[req.params.id]);if(!order)return res.status(404).json({message:'Order not found'});if(order.order_type!=='parcel')return res.status(400).json({message:'Advance payment is only available for parcel orders'});if(order.status==='completed')return res.status(409).json({message:'Parcel is already completed'});const bill=await billFor(order.id,conn);await conn.query("UPDATE orders SET payment_status='paid',payment_method=?,subtotal=?,tax=?,service_charge=?,total=? WHERE id=?",[req.body.paymentMethod,bill.subtotal,bill.tax,bill.service,bill.total,order.id]);await conn.commit();res.json({id:order.id,paymentStatus:'paid',paymentMethod:req.body.paymentMethod,bill})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.patch('/api/orders/:id/items/status', asyncRoute(async(req,res)=>{if(!['chef','juicer'].includes(portalRole))return res.status(403).json({message:'Chef or Juicer access required'});const status=req.body.status;if(!['new','preparing','ready'].includes(status))return res.status(400).json({message:'Invalid preparation status'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[lines]=await conn.query('SELECT oi.id,m.category FROM order_items oi JOIN menu_items m ON m.id=oi.menu_id WHERE oi.order_id=? FOR UPDATE',[req.params.id]);const ids=lines.filter(line=>portalRole==='juicer'?isJuiceCategory(line.category):!isJuiceCategory(line.category)).map(line=>line.id);if(!ids.length)throw Object.assign(new Error(`This order has no ${portalRole==='juicer'?'juice':'food'} items`),{status:404});await conn.query(`UPDATE order_items SET production_status=? WHERE id IN (${ids.map(()=>'?').join(',')})`,[status,...ids]);const orderStatus=await refreshOrderProductionStatus(req.params.id,conn);await conn.commit();res.json({ok:true,status,orderStatus,updatedItems:ids.length})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.patch('/api/orders/:id/status', asyncRoute(async(req,res)=>{const allowed=['new','preparing','ready','served'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid status'});if(['chef','juicer'].includes(portalRole)&&req.body.status!=='served')return res.status(409).json({message:'Use the department item status endpoint'});await pool.query('UPDATE orders SET status=? WHERE id=?',[req.body.status,req.params.id]);res.json({ok:true})}));
app.post('/api/orders/:id/request-bill',asyncRoute(async(req,res)=>{if(portalRole!=='waiter')return res.status(403).json({message:'Billing requests must come from the Waiter portal'});const[[order]]=await pool.query('SELECT id,table_id tableId,status,payment_status paymentStatus FROM orders WHERE id=?',[req.params.id]);if(!order)return res.status(404).json({message:'Order not found'});if(order.paymentStatus==='paid'||order.status==='completed')return res.status(409).json({message:'This order is already completed'});if(!['ready','served','billing_requested'].includes(order.status))return res.status(409).json({message:'Wait until the kitchen completes this order'});await pool.query("UPDATE orders SET status='billing_requested' WHERE id=?",[order.id]);res.json({ok:true,orderId:order.id,tableId:order.tableId,bill:await billFor(order.id)})}));
app.get('/api/orders/:id/bill', asyncRoute(async(req,res)=>{const [[order]]=await pool.query("SELECT o.*,(SELECT COUNT(*) FROM orders daily WHERE DATE(daily.created_at)=DATE(o.created_at) AND daily.id<=o.id) dailyNumber FROM orders o WHERE o.id=?",[req.params.id]);if(!order)return res.status(404).json({message:'Order not found'});res.json({...await billFor(order.id),order})}));
app.post('/api/orders/:id/finalize', asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Only Admin can finalize payments'});const bill=await billFor(req.params.id),conn=await pool.getConnection();try{await conn.beginTransaction();const [[order]]=await conn.query('SELECT * FROM orders WHERE id=? FOR UPDATE',[req.params.id]);if(!order)return res.status(404).json({message:'Order not found'});const alreadyPaid=order.payment_status==='paid',paymentMethod=alreadyPaid?order.payment_method:(req.body.paymentMethod||null);if(!paymentMethod)return res.status(400).json({message:'Record Cash or Card / UPI payment before completing this order'});await conn.query("UPDATE orders SET status='completed',payment_status='paid',payment_method=?,subtotal=?,tax=?,service_charge=?,total=?,completed_at=NOW() WHERE id=?",[paymentMethod,bill.subtotal,bill.tax,bill.service,bill.total,order.id]);if(order.table_id)await conn.query("UPDATE restaurant_tables SET status='cleaning',guest_name='',booking_time='',order_id=NULL WHERE id=?",[order.table_id]);await conn.commit();res.json({id:order.id,paymentStatus:'paid',paymentMethod,bill})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.post('/api/inventory',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const{name,category='',quantity=0,unit,min=0,cost=0}=req.body;if(!name||!unit||Number(quantity)<0||Number(min)<0||Number(cost)<0)return res.status(400).json({message:'Name, unit, and valid quantities are required'});const[result]=await pool.query('INSERT INTO inventory (name,category,quantity,unit,min_quantity,cost) VALUES (?,?,?,?,?,?)',[name,category,Number(quantity),unit,Number(min),Number(cost)]);if(Number(quantity)>0)await pool.query("INSERT INTO inventory_transactions (inventory_id,movement_type,quantity,unit_cost,note,created_by) VALUES (?,'purchase',?,?,?,?)",[result.insertId,Number(quantity),Number(cost),'Opening stock',req.body.createdBy||'Admin']);res.status(201).json({id:result.insertId})}));
app.put('/api/inventory/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const{name,category='',unit,min=0,cost=0}=req.body;await pool.query('UPDATE inventory SET name=?,category=?,unit=?,min_quantity=?,cost=? WHERE id=?',[name,category,unit,Number(min),Number(cost),req.params.id]);res.json({ok:true})}));
app.post('/api/inventory/:id/movements',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const type=req.body.movementType,quantity=Number(req.body.quantity);if(!['purchase','usage','adjustment','waste'].includes(type)||!Number.isFinite(quantity)||quantity<=0)return res.status(400).json({message:'Choose a movement type and enter a positive quantity'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[[item]]=await conn.query('SELECT id,quantity,cost FROM inventory WHERE id=? FOR UPDATE',[req.params.id]);if(!item)throw Object.assign(new Error('Stock item not found'),{status:404});const delta=type==='purchase'?quantity:type==='adjustment'?Number(req.body.adjustmentDirection)==-1?-quantity:quantity:-quantity,newQuantity=Number(item.quantity)+delta;if(newQuantity<0)throw Object.assign(new Error('Not enough stock for this movement'),{status:409});const unitCost=req.body.unitCost===''||req.body.unitCost==null?Number(item.cost):Number(req.body.unitCost);await conn.query('UPDATE inventory SET quantity=?,cost=IF(?="purchase",?,cost) WHERE id=?',[newQuantity,type,unitCost,item.id]);await conn.query('INSERT INTO inventory_transactions (inventory_id,movement_type,quantity,unit_cost,note,created_by) VALUES (?,?,?,?,?,?)',[item.id,type,delta,unitCost,req.body.note||'',req.body.createdBy||'Admin']);await conn.commit();res.status(201).json({ok:true,quantity:newQuantity})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.delete('/api/inventory/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const[[used]]=await pool.query('SELECT id FROM inventory_transactions WHERE inventory_id=? LIMIT 1',[req.params.id]);if(used)return res.status(409).json({message:'Items with stock history cannot be deleted'});await pool.query('DELETE FROM inventory WHERE id=?',[req.params.id]);res.json({ok:true})}));
app.post('/api/finance',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const{entryType,category,description,amount,paymentMethod='Cash',entryDate,reference='',createdBy='Admin'}=req.body;if(!['income','expense'].includes(entryType)||!category||!description||Number(amount)<=0||!entryDate)return res.status(400).json({message:'Type, category, description, amount, and date are required'});const[result]=await pool.query('INSERT INTO finance_entries (entry_type,category,description,amount,payment_method,entry_date,reference,created_by) VALUES (?,?,?,?,?,?,?,?)',[entryType,category,description,Number(amount),paymentMethod,entryDate,reference,createdBy]);res.status(201).json({id:result.insertId})}));
app.delete('/api/finance/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});await pool.query('DELETE FROM finance_entries WHERE id=?',[req.params.id]);res.json({ok:true})}));
app.post('/api/supplier-purchases',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const{supplierName,invoiceNumber='',description,purchaseDate,totalAmount,paidAmount=0,paymentMethod='Cash',reference='',notes='',createdBy='Admin'}=req.body,total=Number(totalAmount),paid=Number(paidAmount);if(!supplierName||!description||!purchaseDate||total<=0||paid<0||paid>total)return res.status(400).json({message:'Supplier, description, date, valid total, and paid amount are required'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[result]=await conn.query('INSERT INTO supplier_purchases (supplier_name,invoice_number,description,purchase_date,total_amount,notes,created_by) VALUES (?,?,?,?,?,?,?)',[supplierName,invoiceNumber,description,purchaseDate,total,notes,createdBy]);if(paid>0)await conn.query('INSERT INTO supplier_payments (purchase_id,amount,payment_method,payment_date,reference,notes,created_by) VALUES (?,?,?,?,?,?,?)',[result.insertId,paid,paymentMethod,purchaseDate,reference,'Payment recorded with purchase',createdBy]);await conn.commit();res.status(201).json({id:result.insertId,totalAmount:total,paidAmount:paid,dueAmount:total-paid})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.post('/api/supplier-purchases/:id/payments',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const amount=Number(req.body.amount);if(amount<=0||!req.body.paymentDate)return res.status(400).json({message:'A positive payment amount and payment date are required'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[[purchase]]=await conn.query('SELECT id,total_amount totalAmount FROM supplier_purchases WHERE id=? FOR UPDATE',[req.params.id]);if(!purchase)throw Object.assign(new Error('Supplier purchase not found'),{status:404});const[[totals]]=await conn.query('SELECT COALESCE(SUM(amount),0) paid FROM supplier_payments WHERE purchase_id=?',[purchase.id]);const due=Number(purchase.totalAmount)-Number(totals.paid);if(amount>due)throw Object.assign(new Error(`Payment exceeds outstanding balance of ${due.toFixed(2)}`),{status:409});const[result]=await conn.query('INSERT INTO supplier_payments (purchase_id,amount,payment_method,payment_date,reference,notes,created_by) VALUES (?,?,?,?,?,?,?)',[purchase.id,amount,req.body.paymentMethod||'Cash',req.body.paymentDate,req.body.reference||'',req.body.notes||'',req.body.createdBy||'Admin']);await conn.commit();res.status(201).json({id:result.insertId,paidAmount:Number(totals.paid)+amount,dueAmount:due-amount})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.delete('/api/supplier-purchases/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query('DELETE FROM supplier_payments WHERE purchase_id=?',[req.params.id]);await conn.query('DELETE FROM supplier_purchases WHERE id=?',[req.params.id]);await conn.commit();res.json({ok:true})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.put('/api/settings', asyncRoute(async(req,res)=>{await pool.query('UPDATE settings SET hotel_name=?,tax_rate=?,service_charge=?,currency=? WHERE id=1',[req.body.hotelName,req.body.taxRate,req.body.serviceCharge,req.body.currency]);res.json({ok:true})}));
async function verifyPortalStaff(userId){const[[staff]]=await pool.query('SELECT id,name,role FROM users WHERE id=? AND active=1 AND deleted_at IS NULL',[userId]);if(!staff)return null;if(portalRole!=='admin'&&staff.role!==portalRole)return null;return staff}
app.get('/api/attendance/:id',asyncRoute(async(req,res)=>{const staff=await verifyPortalStaff(req.params.id);if(!staff)return res.status(403).json({message:'This staff account does not belong to this portal'});const[shifts]=await pool.query('SELECT id,check_in checkIn,check_out checkOut,notes FROM staff_attendance WHERE user_id=? ORDER BY check_in DESC LIMIT 100',[staff.id]);res.json({staff,shifts,activeShift:shifts.find(s=>!s.checkOut)||null})}));
app.post('/api/attendance/:id/check-in',asyncRoute(async(req,res)=>{const staff=await verifyPortalStaff(req.params.id);if(!staff)return res.status(403).json({message:'This staff account does not belong to this portal'});if(portalRole==='admin')return res.status(403).json({message:'Staff must check in from their own portal'});const[[open]]=await pool.query('SELECT id FROM staff_attendance WHERE user_id=? AND check_out IS NULL',[staff.id]);if(open)return res.status(409).json({message:'You are already checked in'});const[result]=await pool.query('INSERT INTO staff_attendance (user_id,check_in,notes) VALUES (?,NOW(),?)',[staff.id,req.body.notes||'']);res.status(201).json({id:result.insertId,checkIn:new Date()})}));
app.post('/api/attendance/:id/check-out',asyncRoute(async(req,res)=>{const staff=await verifyPortalStaff(req.params.id);if(!staff)return res.status(403).json({message:'This staff account does not belong to this portal'});if(portalRole==='admin')return res.status(403).json({message:'Staff must check out from their own portal'});const[[shift]]=await pool.query('SELECT id FROM staff_attendance WHERE user_id=? AND check_out IS NULL ORDER BY check_in DESC LIMIT 1',[staff.id]);if(!shift)return res.status(409).json({message:'You are not currently checked in'});await pool.query('UPDATE staff_attendance SET check_out=NOW(),notes=IF(?="",notes,?) WHERE id=?',[req.body.notes||'',req.body.notes||'',shift.id]);res.json({ok:true,checkOut:new Date()})}));
app.post('/api/staff',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const{name,role,pin,phone='',payType='monthly',payRate=0}=req.body;if(!name||!['admin','waiter','chef'].includes(role)||!/^[0-9]{6}$/.test(pin)||!['daily','monthly'].includes(payType))return res.status(400).json({message:'Name, role, Daily/Monthly salary basis, and a unique 6-digit PIN are required'});if(['admin','chef'].includes(role)){const[[existing]]=await pool.query('SELECT id FROM users WHERE role=? AND deleted_at IS NULL LIMIT 1',[role]);if(existing)return res.status(409).json({message:role==='admin'?'This company already has its single Admin login.':'This company already has its single Head Chef login. Add other chefs from Chef Management without PINs.'})}const currentDatabase=String(req.headers['x-company-database']||process.env.DB_NAME||'knockout');await ensureUniquePortalPin({pin,currentDatabase});const[result]=await pool.query('INSERT INTO users (name,role,pin,phone,pay_type,pay_rate,active) VALUES (?,?,?,?,?,?,TRUE)',[name,role,pin,phone,payType,Number(payRate)]);res.status(201).json({id:result.insertId})}));
app.put('/api/staff/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const{name,role,pin,phone='',payType='monthly',payRate=0,active=true}=req.body;if(!['admin','waiter','chef','juicer'].includes(role)||!/^[0-9]{6}$/.test(String(pin||''))||!['daily','monthly'].includes(payType))return res.status(400).json({message:'Valid role, unique 6-digit PIN, and Daily/Monthly salary basis are required'});if(['admin','chef','juicer'].includes(role)){const[[existing]]=await pool.query('SELECT id FROM users WHERE role=? AND id<>? AND deleted_at IS NULL LIMIT 1',[role,req.params.id]);if(existing)return res.status(409).json({message:`This company already has its single ${role==='admin'?'Admin':role==='chef'?'Head Chef':'Juicer'} login.`})}const currentDatabase=String(req.headers['x-company-database']||process.env.DB_NAME||'knockout');if(active)await ensureUniquePortalPin({pin,currentDatabase,excludeId:req.params.id});const[result]=await pool.query('UPDATE users SET name=?,role=?,pin=?,phone=?,pay_type=?,pay_rate=?,active=? WHERE id=? AND deleted_at IS NULL',[name,role,pin,phone,payType,Number(payRate),!!active,req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Staff member not found'});res.json({ok:true})}));
app.delete('/api/staff/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const[[staff]]=await pool.query('SELECT id,name,role FROM users WHERE id=? AND deleted_at IS NULL',[req.params.id]);if(!staff)return res.status(404).json({message:'Staff member not found'});if(staff.role==='admin')return res.status(409).json({message:'The company Admin login is protected and cannot be deleted here'});await pool.query("UPDATE users SET active=FALSE,deleted_at=NOW(),pin=CONCAT('deleted-',id,'-',UNIX_TIMESTAMP()) WHERE id=?",[staff.id]);res.json({ok:true,id:staff.id,name:staff.name,attendancePreserved:true})}));
app.get('/api/juicer-login',asyncRoute(async(_req,res)=>{if(portalRole!=='chef')return res.status(403).json({message:'Head Chef access required'});const[[juicer]]=await pool.query("SELECT id,name,role,pin,phone,pay_type payType,pay_rate payRate,active FROM users WHERE role='juicer' AND deleted_at IS NULL LIMIT 1");res.json(juicer||null)}));
app.post('/api/juicer-login',asyncRoute(async(req,res)=>{if(portalRole!=='chef')return res.status(403).json({message:'Only the Head Chef can create the Juicer login'});const{name,pin,phone='',payType='monthly',payRate=0}=req.body;if(!String(name||'').trim()||!/^[0-9]{6}$/.test(String(pin||''))||!['daily','monthly'].includes(payType))return res.status(400).json({message:'Name, unique 6-digit PIN, and salary basis are required'});const[[existing]]=await pool.query("SELECT id FROM users WHERE role='juicer' AND deleted_at IS NULL LIMIT 1");if(existing)return res.status(409).json({message:'This company already has its single Juicer login. Admin can edit it from Staff Management.'});const currentDatabase=String(req.headers['x-company-database']||process.env.DB_NAME||'knockout');await ensureUniquePortalPin({pin,currentDatabase});const[result]=await pool.query("INSERT INTO users (name,role,pin,phone,pay_type,pay_rate,active) VALUES (?,'juicer',?,?,?,?,TRUE)",[name.trim(),pin,phone.trim(),payType,Number(payRate)]);res.status(201).json({id:result.insertId,role:'juicer'})}));
app.post('/api/kitchen-staff',asyncRoute(async(req,res)=>{if(!['admin','chef'].includes(portalRole))return res.status(403).json({message:'Admin or Head Chef access required'});const{name,designation='Chef',phone='',specialization='',payType='monthly',payRate=0,joinedOn=null,notes='',createdBy=portalRole==='admin'?'Admin':'Head Chef'}=req.body;if(!String(name||'').trim()||!String(designation||'').trim()||!['daily','monthly'].includes(payType))return res.status(400).json({message:'Chef name, designation, and Daily/Monthly salary basis are required'});const[result]=await pool.query('INSERT INTO kitchen_staff (name,designation,phone,specialization,pay_type,pay_rate,joined_on,notes,active,created_by) VALUES (?,?,?,?,?,?,?,?,TRUE,?)',[name.trim(),designation.trim(),phone.trim(),specialization.trim(),payType,Number(payRate),joinedOn||null,notes.trim(),createdBy]);res.status(201).json({id:result.insertId})}));
app.put('/api/kitchen-staff/:id',asyncRoute(async(req,res)=>{if(!['admin','chef'].includes(portalRole))return res.status(403).json({message:'Admin or Head Chef access required'});const{name,designation='Chef',phone='',specialization='',payType='monthly',payRate=0,joinedOn=null,notes='',active=true}=req.body;if(!String(name||'').trim()||!String(designation||'').trim()||!['daily','monthly'].includes(payType))return res.status(400).json({message:'Chef name, designation, and Daily/Monthly salary basis are required'});const[result]=await pool.query('UPDATE kitchen_staff SET name=?,designation=?,phone=?,specialization=?,pay_type=?,pay_rate=?,joined_on=?,notes=?,active=? WHERE id=?',[name.trim(),designation.trim(),phone.trim(),specialization.trim(),payType,Number(payRate),joinedOn||null,notes.trim(),!!active,req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Kitchen staff member not found'});res.json({ok:true})}));
app.delete('/api/kitchen-staff/:id',asyncRoute(async(req,res)=>{if(!['admin','chef'].includes(portalRole))return res.status(403).json({message:'Admin or Head Chef access required'});const[result]=await pool.query('DELETE FROM kitchen_staff WHERE id=?',[req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Kitchen staff member not found'});res.json({ok:true})}));
app.post('/api/staff/:id/check-in',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const[[staff]]=await pool.query('SELECT id FROM users WHERE id=? AND active=1',[req.params.id]);if(!staff)return res.status(404).json({message:'Active staff member not found'});const[[open]]=await pool.query('SELECT id FROM staff_attendance WHERE user_id=? AND check_out IS NULL',[req.params.id]);if(open)return res.status(409).json({message:'Staff member is already checked in'});const[result]=await pool.query('INSERT INTO staff_attendance (user_id,check_in,notes) VALUES (?,NOW(),?)',[req.params.id,req.body.notes||'']);res.status(201).json({id:result.insertId})}));
app.post('/api/staff/:id/check-out',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const[[shift]]=await pool.query('SELECT id FROM staff_attendance WHERE user_id=? AND check_out IS NULL ORDER BY check_in DESC LIMIT 1',[req.params.id]);if(!shift)return res.status(409).json({message:'No active check-in found'});await pool.query('UPDATE staff_attendance SET check_out=NOW(),notes=IF(?="",notes,?) WHERE id=?',[req.body.notes||'',req.body.notes||'',shift.id]);res.json({ok:true})}));
app.post('/api/menu',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const {name,category,description='',price,icon='🍽️',available=true}=req.body;if(!name||!category||Number(price)<0)return res.status(400).json({message:'Name, category, and valid price are required'});const[result]=await pool.query('INSERT INTO menu_items (name,category,description,price,icon,available,is_combo) VALUES (?,?,?,?,?,?,FALSE)',[name,category,description,Number(price),icon,!!available]);res.status(201).json({id:result.insertId})}));
app.put('/api/menu/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const {name,category,description='',price,icon='🍽️',available=true}=req.body;await pool.query('UPDATE menu_items SET name=?,category=?,description=?,price=?,icon=?,available=? WHERE id=?',[name,category,description,Number(price),icon,!!available,req.params.id]);res.json({ok:true})}));
app.delete('/api/menu/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});await pool.query('UPDATE menu_items SET available=FALSE WHERE id=?',[req.params.id]);res.json({ok:true})}));
app.patch('/api/menu/:id/availability',asyncRoute(async(req,res)=>{if(!['admin','chef','juicer'].includes(portalRole))return res.status(403).json({message:'Admin, Head Chef, or Juicer access required'});if(typeof req.body.available!=='boolean')return res.status(400).json({message:'Availability must be true or false'});if(portalRole==='juicer'){const[[item]]=await pool.query('SELECT category FROM menu_items WHERE id=?',[req.params.id]);if(!item||!isJuiceCategory(item.category))return res.status(403).json({message:'Juicer can only update juice availability'})}const[result]=await pool.query('UPDATE menu_items SET available=? WHERE id=?',[req.body.available,req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Dish not found'});res.json({ok:true,id:Number(req.params.id),available:req.body.available})}));
app.post('/api/combos',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const {name,description='',price,icon='🎁',components=[]}=req.body;if(!name||Number(price)<0||!components.length)return res.status(400).json({message:'Combo name, price, and at least one item are required'});const conn=await pool.getConnection();try{await conn.beginTransaction();const[result]=await conn.query("INSERT INTO menu_items (name,category,description,price,icon,available,is_combo) VALUES (?,'Combo Offers',?,?,?,TRUE,TRUE)",[name,description,Number(price),icon]);for(const component of components){const[[item]]=await conn.query('SELECT id FROM menu_items WHERE id=? AND is_combo=FALSE',[component.menuId]);if(!item)throw new Error('A selected combo item is invalid');await conn.query('INSERT INTO combo_components (combo_id,menu_id,quantity) VALUES (?,?,?)',[result.insertId,component.menuId,Math.max(1,Number(component.quantity)||1)])}await conn.commit();res.status(201).json({id:result.insertId})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.put('/api/combos/:id',asyncRoute(async(req,res)=>{if(portalRole!=='admin')return res.status(403).json({message:'Admin access required'});const {name,description='',price,icon='🎁',components=[]}=req.body;const conn=await pool.getConnection();try{await conn.beginTransaction();await conn.query("UPDATE menu_items SET name=?,category='Combo Offers',description=?,price=?,icon=?,available=TRUE,is_combo=TRUE WHERE id=?",[name,description,Number(price),icon,req.params.id]);await conn.query('DELETE FROM combo_components WHERE combo_id=?',[req.params.id]);for(const component of components)await conn.query('INSERT INTO combo_components (combo_id,menu_id,quantity) VALUES (?,?,?)',[req.params.id,component.menuId,Math.max(1,Number(component.quantity)||1)]);await conn.commit();res.json({ok:true})}catch(e){await conn.rollback();throw e}finally{conn.release()}}));
app.post('/api/menu/:id/image',upload.single('image'),asyncRoute(async(req,res)=>{if(!req.file)return res.status(400).json({message:'Please select an image file'});const [[item]]=await pool.query('SELECT image_object imageObject FROM menu_items WHERE id=?',[req.params.id]);if(!item)return res.status(404).json({message:'Menu item not found'});const ext=req.file.originalname.split('.').pop()?.replace(/[^a-zA-Z0-9]/g,'')||'jpg',objectName=`menu/${req.params.id}-${crypto.randomUUID()}.${ext}`;await minio.putObject(bucket,objectName,req.file.buffer,req.file.size,{'Content-Type':req.file.mimetype});if(item.imageObject)await minio.removeObject(bucket,item.imageObject).catch(()=>{});const imageUrl=publicUrl(objectName);await pool.query('UPDATE menu_items SET image_url=?,image_object=? WHERE id=?',[imageUrl,objectName,req.params.id]);res.json({imageUrl,objectName})}));
app.delete('/api/menu/:id/image',asyncRoute(async(req,res)=>{const [[item]]=await pool.query('SELECT image_object imageObject FROM menu_items WHERE id=?',[req.params.id]);if(item?.imageObject)await minio.removeObject(bucket,item.imageObject);await pool.query('UPDATE menu_items SET image_url=NULL,image_object=NULL WHERE id=?',[req.params.id]);res.json({ok:true})}));
app.use((error,_req,res,_next)=>{console.error(error);res.status(error.status||500).json({message:error.message||'Server error'})});

const port=process.env.PORT||4000;
async function start(){for(let i=0;i<30;i++){try{await migrate();await initializeStorage();app.listen(port,()=>console.log(`KnockOUT API on http://localhost:${port}`));return}catch(e){console.log(`Waiting for services (${i+1}/30): ${e.message}`);await new Promise(r=>setTimeout(r,3000))}}process.exit(1)}
start();
