import { useState } from 'react';
import { ArrowRight, Check, Armchair, ChefHat, ReceiptText, Users, CupSoda, Smartphone, CalendarDays, Package, UtensilsCrossed, Boxes, Wallet, Settings } from 'lucide-react';
import './landing-workspace.css';

const roles = [
  { name: 'Admin', icon: Settings, title: 'See the service. Steer the business.', copy: 'Move from the restaurant floor to billing, stock and daily finances. Keep the operational details in view without stepping into every station’s queue.', tasks: ['Manage tables and timed table bookings', 'Create parcels and record payments', 'Review stock, suppliers and daily closing'], screen: 'Your operational overview', cards: [['Floor','Available · Occupied · Cleaning'],['Orders','Dine-in · Parcel · Billing'],['Business','Stock · Finance · Staff']] },
  { name: 'Waiter', icon: Armchair, title: 'More attention for the table.', copy: 'Choose a table, send an order and add another round when guests are ready. Follow the handoff and request the bill when service is complete.', tasks: ['Build orders from available menu items', 'Track rounds and confirm receipt', 'Request the bill for Admin settlement'], screen: 'Your service, one table at a time', cards: [['Table 02','Open the table workspace'],['Round 02','Add dishes and drinks'],['Handoff','Confirm receipt at the table']] },
  { name: 'Chef', icon: ChefHat, title: 'A clear queue. A calmer kitchen.', copy: 'Work through food tickets for tables and parcels. Mark preparation progress, confirm collection and request stock from the web workspace.', tasks: ['Prepare food by order round', 'Mark food ready and confirm collection', 'Manage dish availability and request stock'], screen: 'Your kitchen, in sequence', cards: [['New','Review the next food round'],['Preparing','Keep the team informed'],['Ready','Confirm collection when the round is ready']] },
  { name: 'Juicer', icon: CupSoda, title: 'Keep the drinks in the flow.', copy: 'Give the juice station its own focused workspace. Review drink items, update preparation status and keep availability current.', tasks: ['See the juice preparation queue', 'Move items from preparing to ready', 'Update availability for juice items'], screen: 'Your station, your priorities', cards: [['Juices','Manage what is available'],['Queue','Prepare the next drink items'],['Ready','Let the team know drinks are ready']] },
];
const modules = [
  ['Before service', CalendarDays, 'Table bookings', 'Choose a table, date, time and duration. Keep a contact phone with the reservation.'],
  ['Before service', UtensilsCrossed, 'Menu & combos', 'Create dishes and combos, upload food images, set prices and manage availability.'],
  ['During service', Armchair, 'Floor & order rounds', 'Follow table status and keep additional orders organised into separate rounds.'],
  ['During service', ChefHat, 'Kitchen & juice', 'Dedicated production queues keep food and drink preparation in focus.'],
  ['During service', Package, 'Parcel operations', 'Build takeaway orders, follow preparation and manage payment and collection.'],
  ['After service', ReceiptText, 'Billing & receipts', 'Request the bill, record payment and print a receipt from the web workspace.'],
  ['After service', Wallet, 'Finance & suppliers', 'Record income, expenses, purchases and supplier payments. Review outstanding balances.'],
  ['Behind the scenes', Boxes, 'Stock & requests', 'Record purchases, usage, waste and adjustments. Review low stock and kitchen requests.'],
  ['Behind the scenes', Users, 'Staff & attendance', 'Manage login users and kitchen staff. Team members record shifts in the mobile app.'],
];

export function TeamStory() {
  const [selected, setSelected] = useState(0);
  const role = roles[selected];
  function keyboard(event,index) {
    const next = event.key === 'ArrowRight' ? (index+1)%roles.length : event.key === 'ArrowLeft' ? (index+roles.length-1)%roles.length : event.key === 'Home' ? 0 : event.key === 'End' ? roles.length-1 : null;
    if(next === null) return;
    event.preventDefault();setSelected(next);document.getElementById(`story-role-${next}`).focus();
  }
  return <section className="workspace-team" id="your-team"><div className="workspace-heading"><span className="story-eyebrow">SAME SERVICE. DIFFERENT PERSPECTIVES.</span><h2>One team.<br/><em>Everyone in their element.</em></h2><p>Explore how each role moves the story forward.</p></div><div className="workspace-role-tabs" role="tablist" aria-label="Explore staff roles">{roles.map(({name,icon:Icon},index)=><button id={`story-role-${index}`} key={name} role="tab" aria-selected={selected===index} aria-controls="story-role-panel" tabIndex={selected===index?0:-1} onKeyDown={event=>keyboard(event,index)} onClick={()=>setSelected(index)}><Icon size={18}/>{name}</button>)}</div><div className="workspace-role-panel" id="story-role-panel" role="tabpanel" aria-labelledby={`story-role-${selected}`}><div className="workspace-role-copy"><span className="story-eyebrow">THE {role.name.toUpperCase()} WORKSPACE</span><h3>{role.title}</h3><p>{role.copy}</p><ul>{role.tasks.map(task=><li key={task}><Check size={15}/>{task}</li>)}</ul></div><div className="workspace-role-scene" key={role.name}><div className="workspace-role-window"><header><img className="workspace-mini-logo" src="/knockout-logo.png" alt=""/><span>{role.name}<small>Illustrative workspace</small></span><role.icon size={22}/></header><h4>{role.screen}</h4>{role.cards.map(([label,detail],i)=><div className="workspace-role-row" key={label}><span>0{i+1}</span><div><strong>{label}</strong><small>{detail}</small></div><ArrowRight size={14}/></div>)}<footer>Focused tools for the work in front of you.</footer></div></div></div></section>;
}

export function WorkspaceExplorer() {
  const [filter,setFilter] = useState('All');
  return <section className="workspace-explorer" id="workspace-explorer"><div className="workspace-heading"><span className="story-eyebrow">THE FULL PICTURE</span><h2>From opening the doors<br/><em>to closing the books.</em></h2><p>Explore the tools behind each part of your day.</p></div><div className="workspace-filters" role="group" aria-label="Filter workspace capabilities">{['All','Before service','During service','After service','Behind the scenes'].map(label=><button key={label} aria-pressed={filter===label} onClick={()=>setFilter(label)}>{label}</button>)}</div><div className="workspace-module-grid">{modules.filter(([group])=>filter==='All'||group===filter).map(([group,Icon,title,copy])=><article key={title}><Icon size={23}/><small>{group}</small><h3>{title}</h3><p>{copy}</p></article>)}</div></section>;
}

export function BusinessStory() {
  return <section className="workspace-business"><div className="workspace-finance-scene"><div className="workspace-finance-card"><header><Wallet size={19}/><span>DAILY CLOSING</span><small>Illustrative preview</small></header><h3>Know where the day stands.</h3><div className="workspace-ledger">{[['Sales','Paid bills'],['Inflow','Other income'],['Outflow','Expenses & supplier payments'],['Review','Outstanding supplier balances']].map(([label,description])=><div key={label}><span>{label}</span><b>{description}</b></div>)}</div><div className="workspace-export"><ReceiptText size={16}/> Daily & monthly CSV reports</div></div><div className="workspace-stock-card"><Boxes size={20}/><span><b>A kitchen request, followed through.</b><small>Requested → Ordered → Resolved</small></span></div></div><div className="workspace-business-copy"><span className="story-eyebrow">WHEN SERVICE SLOWS, CLARITY STAYS</span><h2>The details behind<br/><em>a better tomorrow.</em></h2><p>Look beyond the day’s orders. Review supplier balances, record expenses and understand the stock movements your team has entered.</p><div className="workspace-detail"><Boxes size={20}/><div><h3>Replenish with context</h3><p>Review low stock, recorded usage and kitchen requests before recording a purchase.</p></div></div><div className="workspace-detail"><Wallet size={20}/><div><h3>Follow every supplier balance</h3><p>Record a purchase, add a payment and see what remains outstanding.</p></div></div><div className="workspace-detail"><ReceiptText size={20}/><div><h3>Take the numbers with you</h3><p>Export daily finance and monthly revenue reports from the web workspace.</p></div></div></div></section>;
}

export function MobileStory() {
  return <section className="workspace-mobile"><div><span className="story-eyebrow">AT THE DESK. ON THE FLOOR.</span><h2>Your workspace,<br/><em>where the work happens.</em></h2><p>Use the web workspace for detailed operational views and the mobile app for role-specific tasks on the move.</p><ul><li><Check size={16}/> Table service and order progress</li><li><Check size={16}/> Kitchen and juice preparation queues</li><li><Check size={16}/> Staff check-in, check-out and shift history</li></ul><small>Available tools vary by role and platform.</small></div><div className="workspace-phone-scene" aria-label="Illustrative mobile attendance screen"><div className="workspace-phone"><div className="workspace-phone-camera"/><header><img className="workspace-mini-logo" src="/knockout-logo.png" alt=""/><Smartphone size={17}/></header><span className="story-eyebrow">MY WORKDAY</span><h3>Ready for<br/>a good service.</h3><div className="workspace-shift"><Users size={25}/><b>Attendance</b><p>Check in when your shift begins.<br/>Check out when it ends.</p><span>YOUR SHIFT, RECORDED</span></div><div className="workspace-phone-links"><span><Users size={16}/>Attendance</span><span><Armchair size={16}/>Tables</span><span><ReceiptText size={16}/>Orders</span></div><small>Illustrative preview</small></div><div className="workspace-mobile-note"><Check size={18}/><span>One service.<br/><b>A connected team.</b></span></div></div></section>;
}

export function GettingStarted({register}) {
  return <section className="workspace-start" id="getting-started"><div className="workspace-heading"><span className="story-eyebrow">MAKE IT YOUR WORKSPACE</span><h2>A considered start.<br/><em>A connected next chapter.</em></h2><p>From your first application to your team’s first service.</p></div><ol>{[['Tell us about your business','Enter your business and administrator details, then choose a package and subscription period.'],['Follow your application','Use your temporary applicant login to view the review outcome and next steps.'],['Complete your setup','Once approved, finish the requested business and activation details to receive your company credentials.'],['Bring your team together','Set up staff access, your tables and menu, and begin using the modules enabled for your business.']].map(([title,copy],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol><button className="story-button" onClick={register}>Start your application <ArrowRight size={17}/></button></section>;
}
